var STAR_SPEED_FRONT = 50;
var STAR_SPEED_MIDDLE = 25;
var STAR_SPEED_BACK = 12;

var LASER_BULLET_SPEED = 150;

var JET_SPEED_X = 125;
var JET_SPEED_Y = 125;

var ENEMY_SPEED_LOW = 100;
var ENEMY_SPEED_MEDIUM = 125;
var ENEMY_SPEED_HIGH = 150;

var ENEMY_SPAWN_MIN_DELAY = 500;
var ENEMY_SPAWN_MAX_DELAY = 3000;
var ENEMY_SPAWN_DELAY_RANGE = ENEMY_SPAWN_MAX_DELAY - ENEMY_SPAWN_MIN_DELAY;

var FRAMES_PER_SECOND = 1000/24;
